-- Alterar a geração de identity de vendas e pedidos para BY DEFAULT
-- Isso permite inserir números fixos para seeds/testes e ao mesmo tempo continua gerando números automaticamente quando omitido

ALTER TABLE public.vendas ALTER COLUMN numero DROP IDENTITY IF EXISTS;
ALTER TABLE public.vendas ALTER COLUMN numero ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE public.pedidos ALTER COLUMN numero DROP IDENTITY IF EXISTS;
ALTER TABLE public.pedidos ALTER COLUMN numero ADD GENERATED BY DEFAULT AS IDENTITY;
