-- Migration: 20260825000000_create_compras.sql
-- Description: Create compras and itens_compra tables, RLS policies, and RPCs criar_compra, confirmar_compra

-- 1. Tabela compras
CREATE TABLE IF NOT EXISTS public.compras (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  empresa_id uuid NOT NULL REFERENCES public.empresas(id),
  fornecedor_id uuid NOT NULL REFERENCES public.fornecedores(id),
  numero bigint GENERATED BY DEFAULT AS IDENTITY,
  total numeric DEFAULT 0,
  status text NOT NULL DEFAULT 'rascunho' CHECK (status IN ('rascunho','confirmada','cancelada')),
  observacoes text,
  data_compra date DEFAULT CURRENT_DATE,
  forma_pagamento text DEFAULT 'a_prazo',
  vencimento date,
  valor_pago numeric DEFAULT 0,
  created_by uuid REFERENCES public.usuarios(id) ON DELETE SET NULL,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- Índices compras
CREATE INDEX IF NOT EXISTS idx_compras_empresa ON public.compras(empresa_id);
CREATE INDEX IF NOT EXISTS idx_compras_fornecedor ON public.compras(empresa_id, fornecedor_id);

-- Enable RLS on compras
ALTER TABLE public.compras ENABLE ROW LEVEL SECURITY;

-- Policies RLS — compras
DROP POLICY IF EXISTS compras_select_empresa ON public.compras;
CREATE POLICY compras_select_empresa ON public.compras
  FOR SELECT USING (empresa_id = get_my_empresa_id() OR is_master());

DROP POLICY IF EXISTS compras_insert_empresa ON public.compras;
CREATE POLICY compras_insert_empresa ON public.compras
  FOR INSERT WITH CHECK (
    empresa_id = get_my_empresa_id()
    AND (is_master() OR is_admin() OR is_manager_or_above() OR is_operador_or_above())
  );

DROP POLICY IF EXISTS compras_update_empresa ON public.compras;
CREATE POLICY compras_update_empresa ON public.compras
  FOR UPDATE USING (empresa_id = get_my_empresa_id() OR is_master())
  WITH CHECK (empresa_id = get_my_empresa_id() OR is_master());


-- 2. Tabela itens_compra
CREATE TABLE IF NOT EXISTS public.itens_compra (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  empresa_id uuid NOT NULL REFERENCES public.empresas(id),
  compra_id uuid NOT NULL REFERENCES public.compras(id) ON DELETE CASCADE,
  produto_id uuid NOT NULL REFERENCES public.produtos(id),
  quantidade numeric NOT NULL CHECK (quantidade > 0),
  preco_unitario numeric NOT NULL DEFAULT 0,
  subtotal numeric NOT NULL DEFAULT 0
);

-- Índices itens_compra
CREATE INDEX IF NOT EXISTS idx_itens_compra_compra ON public.itens_compra(compra_id);
CREATE INDEX IF NOT EXISTS idx_itens_compra_empresa ON public.itens_compra(empresa_id);

-- Enable RLS on itens_compra
ALTER TABLE public.itens_compra ENABLE ROW LEVEL SECURITY;

-- Policies RLS — itens_compra
DROP POLICY IF EXISTS itens_compra_select_empresa ON public.itens_compra;
CREATE POLICY itens_compra_select_empresa ON public.itens_compra
  FOR SELECT USING (empresa_id = get_my_empresa_id() OR is_master());

DROP POLICY IF EXISTS itens_compra_insert_empresa ON public.itens_compra;
CREATE POLICY itens_compra_insert_empresa ON public.itens_compra
  FOR INSERT WITH CHECK (
    empresa_id = get_my_empresa_id()
    AND (is_master() OR is_admin() OR is_manager_or_above() OR is_operador_or_above())
  );

DROP POLICY IF EXISTS itens_compra_update_empresa ON public.itens_compra;
CREATE POLICY itens_compra_update_empresa ON public.itens_compra
  FOR UPDATE USING (empresa_id = get_my_empresa_id() OR is_master())
  WITH CHECK (empresa_id = get_my_empresa_id() OR is_master());

DROP POLICY IF EXISTS itens_compra_delete_empresa ON public.itens_compra;
CREATE POLICY itens_compra_delete_empresa ON public.itens_compra
  FOR DELETE USING (empresa_id = get_my_empresa_id() OR is_master());


-- 3. RPC criar_compra (Criar rascunho)
CREATE OR REPLACE FUNCTION public.criar_compra(
  p_fornecedor_id uuid,
  p_itens jsonb,
  p_observacoes text DEFAULT '',
  p_data_compra date DEFAULT CURRENT_DATE,
  p_forma_pagamento text DEFAULT 'a_prazo',
  p_vencimento date DEFAULT NULL,
  p_valor_pago numeric DEFAULT 0
) RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE
  v_usuario_id uuid;
  v_empresa_id uuid;
  v_compra_id uuid;
  v_total numeric := 0;
  v_numero bigint;
  v_item jsonb;
  v_subtotal numeric;
  v_novo_item_id uuid;
BEGIN
  -- 1. Autenticação
  IF auth.uid() IS NULL THEN
    RETURN jsonb_build_object('sucesso', false, 'erro', 'Usuário não autenticado.');
  END IF;

  SELECT u.id, u.empresa_id INTO v_usuario_id, v_empresa_id
  FROM public.usuarios u
  WHERE u.auth_user_id = auth.uid() AND u.ativo = true;

  IF v_usuario_id IS NULL THEN
    RETURN jsonb_build_object('sucesso', false, 'erro', 'Usuário não encontrado ou não possui perfil cadastrado.');
  END IF;

  IF v_empresa_id IS NULL THEN
    RETURN jsonb_build_object('sucesso', false, 'erro', 'Usuário não possui empresa vinculada.');
  END IF;

  -- 2. Permissão (mesma regra de entrada de estoque)
  IF NOT public.is_operador_or_above() THEN
    RETURN jsonb_build_object('sucesso', false, 'erro', 'Permissão negada. Você não possui perfil autorizado para criar compras.');
  END IF;

  -- 3. Validar fornecedor
  IF NOT EXISTS (
    SELECT 1 FROM public.fornecedores f
    WHERE f.id = p_fornecedor_id AND f.empresa_id = v_empresa_id AND f.ativo = true
  ) THEN
    RETURN jsonb_build_object('sucesso', false, 'erro', 'Fornecedor inválido ou pertence a outra empresa.');
  END IF;

  -- 4. Validar itens
  IF p_itens IS NULL OR jsonb_array_length(p_itens) = 0 THEN
    RETURN jsonb_build_object('sucesso', false, 'erro', 'A compra deve conter pelo menos um item.');
  END IF;

  -- 5. Inserir cabeçalho (rascunho)
  INSERT INTO public.compras (empresa_id, fornecedor_id, total, status, observacoes, data_compra, forma_pagamento, vencimento, valor_pago, created_by)
  VALUES (v_empresa_id, p_fornecedor_id, 0, 'rascunho', p_observacoes, p_data_compra, p_forma_pagamento, p_vencimento, p_valor_pago, v_usuario_id)
  RETURNING id, numero INTO v_compra_id, v_numero;

  -- 6. Inserir itens e calcular total
  FOR v_item IN SELECT * FROM jsonb_array_elements(p_itens)
  LOOP
    -- Validar produto
    IF NOT EXISTS (
      SELECT 1 FROM public.produtos p
      WHERE p.id = (v_item->>'produto_id')::uuid
        AND p.empresa_id = v_empresa_id
        AND p.ativo = true
    ) THEN
      RAISE EXCEPTION 'Produto inválido ou pertence a outra empresa: %', v_item->>'produto_id';
    END IF;

    IF ((v_item->>'quantidade')::numeric) <= 0 THEN
      RAISE EXCEPTION 'A quantidade deve ser maior que zero.';
    END IF;

    IF ((v_item->>'preco_unitario')::numeric) < 0 THEN
      RAISE EXCEPTION 'O preço unitário não pode ser negativo.';
    END IF;

    v_subtotal := ROUND(((v_item->>'quantidade')::numeric * (v_item->>'preco_unitario')::numeric), 2);

    INSERT INTO public.itens_compra (empresa_id, compra_id, produto_id, quantidade, preco_unitario, subtotal)
    VALUES (v_empresa_id, v_compra_id, (v_item->>'produto_id')::uuid, (v_item->>'quantidade')::numeric, (v_item->>'preco_unitario')::numeric, v_subtotal)
    RETURNING id INTO v_novo_item_id;

    v_total := v_total + v_subtotal;
  END LOOP;

  -- 7. Atualizar total
  UPDATE public.compras SET total = v_total WHERE id = v_compra_id;

  RETURN jsonb_build_object(
    'sucesso', true,
    'compra_id', v_compra_id,
    'numero', v_numero,
    'total', v_total,
    'status', 'rascunho'
  );
END;
$$;


-- 4. RPC confirmar_compra (Atômica: estoque + movimentações + preco_custo + contas_pagar)
CREATE OR REPLACE FUNCTION public.confirmar_compra(
  p_compra_id uuid
) RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE
  v_usuario_id uuid;
  v_empresa_id uuid;
  v_compra record;
  v_item record;
  v_estoque record;
  v_mov_id uuid;
  v_conta_pagar_id uuid;
  v_mov_count integer := 0;
  v_status_atual text;
BEGIN
  -- 1. Autenticação
  IF auth.uid() IS NULL THEN
    RETURN jsonb_build_object('sucesso', false, 'erro', 'Usuário não autenticado.');
  END IF;

  SELECT u.id, u.empresa_id INTO v_usuario_id, v_empresa_id
  FROM public.usuarios u
  WHERE u.auth_user_id = auth.uid() AND u.ativo = true;

  IF v_usuario_id IS NULL THEN
    RETURN jsonb_build_object('sucesso', false, 'erro', 'Usuário não encontrado ou não possui perfil cadastrado.');
  END IF;

  IF v_empresa_id IS NULL THEN
    RETURN jsonb_build_object('sucesso', false, 'erro', 'Usuário não possui empresa vinculada.');
  END IF;

  -- 2. Permissão
  IF NOT public.is_operador_or_above() THEN
    RETURN jsonb_build_object('sucesso', false, 'erro', 'Permissão negada.');
  END IF;

  -- 3. Buscar compra
  SELECT * INTO v_compra FROM public.compras WHERE id = p_compra_id AND empresa_id = v_empresa_id;

  IF v_compra.id IS NULL THEN
    RETURN jsonb_build_object('sucesso', false, 'erro', 'Compra não encontrada.');
  END IF;

  IF v_compra.status != 'rascunho' THEN
    RETURN jsonb_build_object('sucesso', false, 'erro', 'Apenas compras em rascunho podem ser confirmadas. Status atual: ' || v_compra.status);
  END IF;

  -- 4. Processar cada item
  FOR v_item IN
    SELECT ic.*, p.nome AS produto_nome, p.unidade
    FROM public.itens_compra ic
    JOIN public.produtos p ON p.id = ic.produto_id
    WHERE ic.compra_id = p_compra_id
  LOOP
    -- Bloquear estoque para evitar race condition
    SELECT * INTO v_estoque FROM public.estoques
    WHERE produto_id = v_item.produto_id AND empresa_id = v_empresa_id
    FOR UPDATE;

    -- Criar ou atualizar estoque
    IF v_estoque.id IS NULL THEN
      INSERT INTO public.estoques (empresa_id, produto_id, quantidade)
      VALUES (v_empresa_id, v_item.produto_id, v_item.quantidade);
    ELSE
      UPDATE public.estoques SET quantidade = quantidade + v_item.quantidade, updated_at = now()
      WHERE id = v_estoque.id;
    END IF;

    -- Criar movimentação de estoque (entrada)
    INSERT INTO public.movimentacoes_estoque (
      empresa_id, produto_id, fornecedor_id, tipo, quantidade, motivo, referencia_id, usuario_id, created_at
    ) VALUES (
      v_empresa_id, v_item.produto_id, v_compra.fornecedor_id, 'entrada',
      v_item.quantidade,
      'Compra #' || v_compra.numero || ' confirmada',
      p_compra_id, v_usuario_id, now()
    );

    v_mov_count := v_mov_count + 1;

    -- Atualizar preço de custo do produto
    UPDATE public.produtos SET preco_custo = v_item.preco_unitario, updated_at = now()
    WHERE id = v_item.produto_id;
  END LOOP;

  -- 5. Criar conta a pagar (se a prazo ou valor_pago < total)
  IF v_compra.forma_pagamento = 'a_prazo' AND v_compra.valor_pago < v_compra.total THEN
    INSERT INTO public.contas_pagar (
      empresa_id, fornecedor_id, descricao, valor, vencimento, valor_pago, status
    ) VALUES (
      v_empresa_id, v_compra.fornecedor_id,
      'Compra #' || v_compra.numero,
      v_compra.total,
      COALESCE(v_compra.vencimento, (CURRENT_DATE + INTERVAL '30 days')::date),
      COALESCE(v_compra.valor_pago, 0),
      'pendente'
    )
    RETURNING id INTO v_conta_pagar_id;
  END IF;

  -- 6. Atualizar status da compra
  UPDATE public.compras SET status = 'confirmada', updated_at = now() WHERE id = p_compra_id;

  RETURN jsonb_build_object(
    'sucesso', true,
    'compra_id', p_compra_id,
    'numero', v_compra.numero,
    'movimentacoes_criadas', v_mov_count,
    'conta_pagar_id', v_conta_pagar_id
  );
END;
$$;
